<?php
include('header.php');
include('dbconnect.php');
?>
<div class="col-md-12" style="height:680px">
<?php
$userid = $_SESSION['userid'];
$aid = $_POST['address'];
$total = $_SESSION['total'];
$perc = $_SESSION['discountrad'];
$discount = $total*$perc/100;
$_SESSION['delcharge'];
$date = date('d/m/Y');
$time = date('h:i:s');
$cmd7 = "select * from address where aid = '".$aid."'";
$data7 = mysqli_query($conn, $cmd7);
$rownum2 = mysqli_num_rows($data7);
if($rownum2 == 0){
    echo "please choose address before you continue to payment.";
   }else{
$row7 = mysqli_fetch_array($data7);
$address = $row7[1].",  ".$row7[2].",  ".$row7[4].",  ".$row7[5].",  ".$row7[6].",  ".$row7[7];
$billname = $row7[1];
$email = $_SESSION['umail'];

$cmd1 = "insert into orders(address,userid,amount,	orderdate,ordertime,discount) values('".$address."','".$userid."','".$total."','".$date."','".$time."','".$discount."')";
$status1 = mysqli_query($conn, $cmd1);

$cmd2 = "select oid from orders order by oid desc limit 1";
$data2 = mysqli_query($conn ,$cmd2);
$row2 = mysqli_fetch_array($data2);
$_SESSION['orderid'] = $row2['oid'];
$oid = $row2['oid'];

$cmd3 = "select * from cart where custid = '".$userid."'";
$data3 = mysqli_query($conn, $cmd3);
while($row3 = mysqli_fetch_array($data3)){
            $qty = $row3['qty'];
            $cmd4 = "select * from products where proid = '".$row3['proid']."'";
            $data4 =mysqli_query($conn, $cmd4);
            $row4 = mysqli_fetch_array($data4);
            $proname = $row4['proname'];
            $proid =$row4['proid'];
            $price = $row4['price'];
            $stock = $row4['stcavl'];
            $stock1 = $stock-$qty;
         $cmd5 = "insert into orderdetails(orderid,proid,	proname,qty,price) values('".$oid."','".$proid."','".$proname."','".$qty."','".$price."')";
         $status5 = mysqli_query($conn, $cmd5);
         $cmd8 = "UPDATE products SET stcavl='".$stock1."'  WHERE proid = '".$proid."'";
         mysqli_query($conn, $cmd8);
}
$cmd6 = "delete from cart where custid = '".$userid."'";
mysqli_query($conn, $cmd6);
unset($_SESSION['delcharge']);
unset($_SESSION['discountrad']);
unset($_SESSION['discountid']);
unset($_SESSION['total']);
unset($_SESSION['pincode']);
unset($_SESSION['cart']);
unset($_SESSION['discount']);
}
?>

<div class="container sty" style="padding:400px;">
<form action="http://localhost/shoppingo/sucess.php" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="rzp_test_V8tLaUAMt3z6RH" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo $total*100; ?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-order_id="<?php echo $oid; ?>"// Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="Acme Corp"
    data-description="A Wild Sheep Chase is the third novel by Japanese author Haruki Murakami"
    data-image="http://192.168.8.106/shoppingo/images/logo.png"
    data-prefill.name="<?php echo $billname; ?>"
    data-prefill.email="<?php echo $email; ?>"
    data-theme.color="#ffb6c1"
></script>
<input type="hidden" custom="Hidden Element" name="hidden">
</form>
</div>
</div>
<?php
include('footer.php');
?>